applications:
  app:
    source:
      root: /
    type: php:8.2
    build:
      flavor: composer
    web:
      locations:
        "/":
          root: "web"
          passthru: "/index.php"
          index:
            - index.php
        "/wp-content/uploads":
          root: "web/wp-content/uploads"
          scripts: false
          allow: true
    mounts:
      "/web/wp-content/uploads": "shared:files/uploads"
      "/web/wp-content/cache": "shared:files/cache"
    relationships:
      database: "mysql:mysql"
    variables:
      env:
        WP_DEBUG: false
        WP_DEBUG_LOG: false
    hooks:
      build: |
        set -e
        composer install --no-dev --optimize-autoloader
      deploy: |
        set -e
        wp core update-db --allow-root

services:
  mysql:
    type: oracle-mysql:8.0
    disk: 2048